# site settings
title: Atikur Rahman
description: your spatial and data solution
baseurl: "https://mapbd.github.io/atik"
email: "arahman.dcc2@gmail.com"

# default images
navbar_logo: "/img/logos/BNHR-navbar-logo.webp"
default_image: "/img/site/images/BNHR-bg.webp"
favicon: "favicon.ico"

# accounts
facebook: "arpon.nil"
twitter: ""
instagram:
github: ""
linkedin: ""
messenger: "arpon.nil"
mastodon:
mumble:
youtube: ""
discord:

# assets
assets: "https://d1v4x8erby89pz.cloudfront.net"

# collections
collections:
    collection_what_ive_done:
    collection_cv_experience_org:
    collection_cv_experience_ind:
    collection_cv_education:
    collection_upcoming_courses_spatial:
    collection_courses_offered_spatial:
    collection_upcoming_courses_data:
    collection_courses_offered_data:   

# exclude
exclude:
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - assets/img

# include
include:
  - .well-known

# paginator
paginate: 10
paginate_path: "blog/page:num/"

# build settings
markdown: kramdown
highlighter: rouge

# plugins
plugins:
  - github-pages
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo
  - jekyll-site-tag
  - jekyll-sitemap
  - jekyll-redirect-from